name: Auto Update

on: [workflow_dispatch]
  #schedule:
  #  - cron: "0 0 * * WED"

jobs:
  run:
    name: UpdateDB and publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm install

    - name: UpdateDB
      run: npm run-script updatedb
      env:
        LICENSE_KEY: ${{secrets.maxmind_token}}
        
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        message: "UpdateDB"

    - name: Bump Version
      run: npm version patch

    - name: Npm publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
